apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadkgfj1664-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadkgfj1664-tenant-component
    app.kubernetes.io/part-of: loadkgfj1664-tenant-app
  name: loadkgfj1664-tenant-component
  namespace: loadkgfj1664-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadkgfj1664-tenant-component
    weight: null
status: {}
